#!/bin/dash
. girt-helper
if ! test -e "$PWD/.girt"; then
    echo "$0: error: girt repository directory .girt not found" >&2
    exit 1
fi
usage() { echo "usage: $0 <commit>:<filename>" 1>&2; exit 1; }

commit=$(echo "$1"|cut -d':' -f1)
filename=$(echo "$1"|cut -d':' -f2)

load_commit(){
    if [ ! -e "$COMMIT_DIR/$1" ]; then
        echo "$0: error: unknown commit '$1'" >&2
        exit 1
    fi
    while read -r hashed; do
        file=$(echo "$hashed" | cut -f2)
        if [ "$file" = "$2" ]; then
            dir=$(echo "$hashed" | cut -c1-2) # 2 char
            name=$(echo "$hashed" | cut -c3-40)
            break
        fi
    done < "$COMMIT_DIR/$1"

    if [ -n "$dir" ] && [ -n "$name" ]; then
        gunzip -c -n "$BLOB_DIR/$dir/$name"
    else
        echo "$0: error: '$2' not found in commit $1" >&2
        exit 1
    fi
}

[ -z "$commit" ] && [ -z "$filename" ] && {
    usage
}

if ! test -z "$commit"; then
    load_commit "$commit" "$filename"
    exit 0
fi

# current index
while read -r LINE; do
    file=$(echo "$LINE" | cut -f2)
    if [ "$file" = "$filename" ]; then 
        dir=$(echo "$LINE" | cut -c1-2) # 2 char
        name=$(echo "$LINE" | cut -c3-40)
    fi
done < "$INDEX_FILE"

if [ -n "$dir" ] && [ -n "$name" ]; then
    gunzip -c -n "$BLOB_DIR/$dir/$name"
else
    echo "$0: error: '$filename' not found in index" >&2
    exit 1
fi
