#!/bin/dash
if ! test -e ".girt"; then
    echo "fatal: this operation must be run in a work tree" >&2
    exit 1
fi

usage() { echo "usage: $0 [commit]:filename" 1>&2; exit 1; }

commit=$(echo "$1"|cut -d':' -f1)
filename=$(echo "$1"|cut -d':' -f2)

load_commit(){
    while read hashed; do
        file=$(echo "$hashed" | cut -f2)
        if [ "$file" != "$2" ]; then continue 
        fi
        dir=$(echo "$hashed" | cut -c1-2) # 2 char
        name=$(echo "$hashed" | cut -c3-40)

        if (! test -z $dir) && (! test -z name); then
            gunzip -c -n .girt/objects/blob/$dir/$name
        fi
    done < ".girt/objects/commit/$1"
}

if ! test -z "$commit"; then
    load_commit $commit $filename
    exit 0
fi

for file in .girt/objects/commit/*; do
    basename=$(basename $file)
    load_commit $basename $filename
done
