#!/bin/dash
. girt-helper

# check current location
if ! test -e "$PWD/.girt"; then
    echo "$0: error: girt repository directory .girt not found" >&2
    exit 1
fi

if test $# -eq 0 ; then
    echo "usage: $0 <branch>"
    exit 1
fi

if [ ! -d "$BRANCHES_DIR/$1" ]; then
    echo "$0: error: unknown branch '$1'" >&2
    exit 1
fi

commit_number=$(tail -n1 "$COMMITS_FILE" | cut -f1)
dirstatus=$(girt-status)
while read -r LINE; do
    status=$(echo "$LINE" | sed 's/ - /\t/g')
    filename=$(echo "$status" | cut -f1)
    type=$(echo "$status" | cut -f2)

    if [ "$type" = "same as repo" ]; then
        rm "$PWD/$filename"
    fi
done <<EOF
$dirstatus
EOF

echo "$1" > "$HEAD_FILE"
. girt-helper # flush file path

commit_number=$(tail -n1 "$COMMITS_FILE" | cut -f1)

while read -r LINE; do
    filename=$(echo "$LINE" | cut -f2)
    dir=$(echo "$LINE" | cut -c1-2) # 2 char
    name=$(echo "$LINE" | cut -c3-40)

    if [ ! -e "$PWD/$filename" ] && [ -n "$dir" ] && [ -n "$name" ]; then
        gunzip -c -n "$BLOB_DIR/$dir/$name" > "$PWD/$filename"
    fi
done < "$COMMIT_DIR/$commit_number"

# flush index file hash
if [ -e "$TMP_DIR/checkout_unchanged_list.tmp" ]; then
    while read -r LINE; do
        girt-add "$LINE" 2> /dev/null
    done < "$TMP_DIR/checkout_unchanged_list.tmp"
    rm "$TMP_DIR/checkout_unchanged_list.tmp"
fi

echo "Switched to branch '$1'"
