#!/bin/dash

# check current location
if ! test -e "$PWD/.girt"; then
    echo "$0: error: girt repository directory .girt not found" >&2
    exit 1
fi

usage() { echo "usage: $0 [-a] [-m <message>]" 1>&2; exit 1; }

all=false

while getopts ":m:a" o; do
    case "${o}" in
        m)
            message=${OPTARG}
            ;;
        a)
            all=true
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if test -z "$message" ; then 
    usage 
fi

# if [ ! -s "$PWD/.girt/index" ]; then
# # index is empty
#     echo "nothing to commit"
#     exit 0
# fi

if $all; then
    # all files option
    # save all files in index to `$PWD/.girt/objects` and update index
    # girt-add * in index
    while read -r LINE; do
        file=$(echo "$LINE" | cut -f2)
        (sh girt-add "$file")
    done < "$PWD/.girt/index"
fi

commit_number=$(tail -n1 "$PWD/.girt/commits" | cut -f1)
if test -z "$commit_number"; then
    commit_number=-1
else
    if output=$(diff -q "$PWD/.girt/index" "$PWD/.girt/objects/commit/$commit_number"); then
        echo "nothing to commit"
        exit 0
    fi
fi
commit_number=$((commit_number+1))
cp "$PWD/.girt/index" "$PWD/.girt/objects/commit/$commit_number"

printf '%d\t%s\n' "$commit_number" "$message" >> "$PWD/.girt/commits"

echo "Committed as commit $commit_number"
