#!/bin/dash
. girt-helper

if test -e "$PWD/.girt" ; then
    echo "$0: error: .girt already exists" >&2
    exit 1
fi
mkdir -p "$PWD/.girt/tmp" "$COMMIT_DIR" "$BLOB_DIR" "$PWD/.girt/refs/heads"
touch "$HEAD_FILE" "$INDEX_FILE" "$PWD/.girt/commits"
echo "master" > "$HEAD_FILE"
echo "Initialized empty girt repository in .girt"
