#!/bin/dash
. girt-helper

# check current location
if ! test -e "$PWD/.girt"; then
    echo "$0: error: girt repository directory .girt not found" >&2
    exit 1
fi

usage() { echo "usage: $0 [-a] [-m <message>]" 1>&2; exit 1; }

all=false

while getopts ":m:a" o; do
    case "${o}" in
        m)
            message=${OPTARG}
            ;;
        a)
            all=true
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if test -z "$message" ; then 
    usage 
fi

# if [ ! -s "$INDEX_FILE" ]; then
# # index is empty
#     echo "nothing to commit"
#     exit 0
# fi

if $all; then
    # all files option
    # save all files in index to `$PWD/.girt/objects` and update index
    # girt-add * in index
    while read -r LINE; do
        file=$(echo "$LINE" | cut -f2)
        (sh girt-add "$file")
    done < "$INDEX_FILE"
fi

next_commit_number=$(cat "$NEXT_COMMIT_NUMBER_FILE")

last_commit_number=$(tail -n1 "$COMMITS_FILE" | cut -f1)
if test -n "$last_commit_number"; then
    if output=$(diff -q "$INDEX_FILE" "$COMMIT_DIR/$last_commit_number"); then
        echo "nothing to commit"
        exit 0
    fi
fi
cp "$INDEX_FILE" "$COMMIT_DIR/$next_commit_number"

printf '%d\t%s\n' "$next_commit_number" "$message" >> "$COMMITS_FILE"

echo "Committed as commit $next_commit_number"

next_commit_number=$((next_commit_number+1))
echo "$next_commit_number" > "$NEXT_COMMIT_NUMBER_FILE"
