#!/bin/dash
if ! test -e "$PWD/.girt"; then
    echo "$0: error: girt repository directory .girt not found" >&2
    exit 1
fi
usage() { echo "usage: $0 [commit]:filename" 1>&2; exit 1; }

commit=$(echo "$1"|cut -d':' -f1)
filename=$(echo "$1"|cut -d':' -f2)

load_commit(){
    while read -r hashed; do
        file=$(echo "$hashed" | cut -f2)
        if [ "$file" != "$2" ]; then continue 
        fi
        dir=$(echo "$hashed" | cut -c1-2) # 2 char
        name=$(echo "$hashed" | cut -c3-40)

        if (! test -z $dir) && (! test -z $name); then
            gunzip -c -n "$PWD/.girt/objects/blob/$dir/$name"
        fi
    done < "$PWD/.girt/objects/commit/$1"
}

if ! test -z "$commit"; then
    load_commit $commit $filename
    exit 0
fi

# current index
while read -r LINE; do
    file=$(echo "$LINE" | cut -f2)
    if [ "$file" != "$filename" ]; then continue 
    fi
    dir=$(echo "$LINE" | cut -c1-2) # 2 char
    name=$(echo "$LINE" | cut -c3-40)

    if (! test -z $dir) && (! test -z $name); then
        gunzip -c -n "$PWD/.girt/objects/blob/$dir/$name"
    fi
    exit 0
done < $PWD/.girt/index
