#!/bin/dash
. girt-helper
if test $# -eq 0 ; then
    echo "usage: $0 <filenames>"
    exit 1
fi
# check current location
if ! test -e "$PWD/.girt"; then
    echo "$0: error: girt repository directory .girt not found" >&2
    exit 1
fi
for file in "$@"; do
    LINE=$(grep -P "\s*\Q$1\E$" "$INDEX_FILE")
    if ! test -e "$PWD/$file" && test -z "$LINE";then
        echo "$0: error: can not open '$1'" >&2
        continue
    fi
    if ! test -e "$PWD/$file" && test -n "$LINE";then
        # PATCH
        # exist in index but removed in system
        # remove file
        sed -i "/$LINE/d" "$INDEX_FILE"
        continue
    fi
    gzip -c -n "$PWD/$file" > "$PWD/.girt/tmp/compressed_tmp"
    hashed=$(cat "$PWD/.girt/tmp/compressed_tmp"|sha1sum|cut -d' ' -f1)
    dir=$(echo "$hashed" | cut -c1-2) # 2 char
    name=$(echo "$hashed" | cut -c3-40)

    if ! test -e "$BLOB_DIR/$dir"; then
        mkdir -p "$BLOB_DIR/$dir"
    fi
    mv "$PWD/.girt/tmp/compressed_tmp" "$BLOB_DIR/$dir/$name"
    
    # load index file to chack if hash changed
    newFile=true
    while read -r LINE; do
        filename=$(echo "$LINE" | cut -f2)
        hashname=$(echo "$LINE" | cut -f1)
        if [ "$filename" = "$file" ]; then
            newFile=false
            printf "%s\t%s\n" "$hashed" "$filename" >> "$INDEX_FILE.tmp"
        else
            echo "$LINE" >> "$INDEX_FILE.tmp"
        fi
    done < "$INDEX_FILE"

    if $newFile; then
        printf "%s\t%s\n" "$hashed" "$file" >> "$INDEX_FILE.tmp"
    fi

    mv "$INDEX_FILE.tmp" "$INDEX_FILE"


done
